# Generated by Django 5.0.6 on 2024-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='completed',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_code',
            field=models.TextField(),
        ),
    ]
